# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.IntegerField(default=0)),
                ('modelo', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.CharField(max_length=60)),
                ('nome_de_guerra', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
    ]
