# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161015010316 on 2016-10-15 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name=b'Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.IntegerField(default=0, verbose_name=b'Numero de Serie')),
                ('modelo', models.CharField(max_length=200, verbose_name=b'Modelo')),
                ('fabricante', models.CharField(max_length=200, verbose_name=b'Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Cautela_Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_retirada', models.DateTimeField(verbose_name=b'Data de Retirada')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Acessorio')),
            ],
        ),
        migrations.CreateModel(
            name='Cautela_Armamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_retirada', models.DateTimeField(verbose_name=b'Data de Retirada')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Armamento')),
            ],
        ),
        migrations.CreateModel(
            name='Cautela_Municao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_retirada', models.DateTimeField(verbose_name=b'Data de Retirada')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.CharField(max_length=60, verbose_name=b'Posto')),
                ('nome_de_guerra', models.CharField(max_length=120, verbose_name=b'Nome de Guerra')),
            ],
        ),
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibre', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Calibre')),
                ('descricao', models.CharField(max_length=250, verbose_name=b'Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, verbose_name=b'Sigla')),
                ('descricao', models.CharField(max_length=250, verbose_name=b'Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Acessorio')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Armamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Armamento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Municao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
                ('municao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Municao')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva')),
            ],
        ),
        migrations.AddField(
            model_name='militar',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva'),
        ),
        migrations.AddField(
            model_name='cautela_municao',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Militar'),
        ),
        migrations.AddField(
            model_name='cautela_municao',
            name='municao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Municao'),
        ),
        migrations.AddField(
            model_name='cautela_armamento',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Militar'),
        ),
        migrations.AddField(
            model_name='cautela_acessorio',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Militar'),
        ),
    ]
