# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161011220334 on 2016-10-11 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250, verbose_name=b'Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Cautela_Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_retirada', models.DateTimeField(verbose_name=b'Data de Retirada')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Acessorio')),
            ],
        ),
        migrations.CreateModel(
            name='Cautela_Armamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_retirada', models.DateTimeField(verbose_name=b'Data de Retirada')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Cautela_Municao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_retirada', models.DateTimeField(verbose_name=b'Data de Retirada')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Acessorio')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Armamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_Municao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name=b'Quantidade')),
            ],
        ),
        migrations.DeleteModel(
            name='Acessorios',
        ),
        migrations.AddField(
            model_name='militar',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='fabricante',
            field=models.CharField(max_length=200, verbose_name=b'Fabricante'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='modelo',
            field=models.CharField(max_length=200, verbose_name=b'Modelo'),
        ),
        migrations.AlterField(
            model_name='armamento',
            name='numero_de_serie',
            field=models.IntegerField(default=0, verbose_name=b'Numero de Serie'),
        ),
        migrations.AlterField(
            model_name='militar',
            name='nome_de_guerra',
            field=models.CharField(max_length=120, verbose_name=b'Nome de Guerra'),
        ),
        migrations.AlterField(
            model_name='militar',
            name='posto',
            field=models.CharField(max_length=60, verbose_name=b'Posto'),
        ),
        migrations.AlterField(
            model_name='municao',
            name='calibre',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'Calibre'),
        ),
        migrations.AlterField(
            model_name='municao',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name=b'Descricao'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name=b'Descricao'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sigla',
            field=models.CharField(max_length=5, verbose_name=b'Sigla'),
        ),
        migrations.AddField(
            model_name='reserva_municao',
            name='municao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Municao'),
        ),
        migrations.AddField(
            model_name='reserva_municao',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva'),
        ),
        migrations.AddField(
            model_name='reserva_armamento',
            name='armamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Armamento'),
        ),
        migrations.AddField(
            model_name='reserva_armamento',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva'),
        ),
        migrations.AddField(
            model_name='reserva_acessorio',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva'),
        ),
        migrations.AddField(
            model_name='cautela_municao',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Militar'),
        ),
        migrations.AddField(
            model_name='cautela_municao',
            name='municao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Municao'),
        ),
        migrations.AddField(
            model_name='cautela_armamento',
            name='armamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Armamento'),
        ),
        migrations.AddField(
            model_name='cautela_armamento',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Militar'),
        ),
        migrations.AddField(
            model_name='cautela_acessorio',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Militar'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='acessorio',
            field=models.ManyToManyField(through='registro.Reserva_Acessorio', to='registro.Acessorio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='armamento',
            field=models.ManyToManyField(through='registro.Reserva_Armamento', to='registro.Armamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='municao',
            field=models.ManyToManyField(through='registro.Reserva_Municao', to='registro.Municao'),
        ),
    ]
