# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessorios',
            new_name='Acessorio',
        ),
    ]
