# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161007235610 on 2016-10-07 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20161007_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Reserva'),
        ),
    ]
