# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161007235921 on 2016-10-08 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_militar_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautela',
            name='data_de_retirada',
            field=models.DateTimeField(verbose_name=b'Data de Retirada'),
        ),
    ]
