# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161008000048 on 2016-10-08 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20161008_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militar',
            name='cautela',
        ),
        migrations.AddField(
            model_name='cautela',
            name='militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Militar'),
        ),
    ]
