# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161021143717 on 2016-10-21 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20161015_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cautela_acessorio',
            name='acessorio',
        ),
        migrations.RemoveField(
            model_name='cautela_armamento',
            name='armamento',
        ),
        migrations.RemoveField(
            model_name='cautela_municao',
            name='municao',
        ),
    ]
